name: nmkr-support-agent
services:
  - name: api
    dockerfile_path: Dockerfile
    source_dir: .
    github:
      branch: main
      deploy_on_push: true
      repo: your-repo/nmkr-support-v4
    http_port: 8080
    health_check:
      http_path: /health
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: REDIS_URL
        scope: RUN_TIME
        value: ${redis.DATABASE_URL}
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        value: ${OPENAI_API_KEY}
      - key: WEBHOOK_SECRET
        scope: RUN_TIME
        value: ${WEBHOOK_SECRET}
      - key: PORT
        value: "8080"

  - name: worker
    dockerfile_path: Dockerfile
    source_dir: .
    command: rq worker nmkr_support
    envs:
      - key: REDIS_URL
        scope: RUN_TIME
        value: ${redis.DATABASE_URL}
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        value: ${OPENAI_API_KEY}

databases:
  - name: redis
    engine: REDIS
    version: "6"
    production: true 